### ISSUE TITLE
Add Example in journal.md

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/100-days-of-oss-template#1]
Below the template in `journal.md`, add an example, so users have something to help them as they create their journal.

**Comment by Ibinola** [comment]
Hello @BekahHW, I'm interested in contributing to this project. I'd like to work on this issue and add an example to the `journal.md` file as mentioned. If it's okay, I'll get started on it. Thanks!

**Comment by BekahHW** [comment]
It's all you @Ibinola! Let me know if you need help.
