### ISSUE TITLE
Feature:  Table of Contents 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/100-days-of-oss-template#3]
### Type of feature

🍕 Feature

### Current behavior

No, more like a suggestion

### Suggested solution

Adding this feature would make it easier for participants to find their contributions after they finish the challenge. What do you think @BekahHW? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
Hey @CBID2, I think I'm missing the request in this issue. What would make it easier for the contributors to find their contributions?

**Comment by CBID2** [comment]
> Hey @CBID2, I think I'm missing the request in this issue. What would make it easier for the contributors to find their contributions? 

A table of contents file within the template @BekahHW

**Comment by BekahHW** [comment]
Ah, I see. A table of contents. 

What should go in the TOC?

**Comment by CBID2** [comment]
I'm thinking of just formatting it and all participants have to do is fill in the blanks. What do you think @BekahHW?

**Comment by BekahHW** [comment]
@CBID2 do you have an example?

**Comment by CBID2** [comment]
> @CBID2 do you have an example?

Yes. Let me do it as a PR via my computer and then you can review it @BekahHW?

**Comment by BekahHW** [comment]
That sounds great, @CBID2

**Comment by CBID2** [comment]
> That sounds great, @CBID2

Here it is @BekahHW: https://github.com/open-sauced/100-days-of-oss-template/pull/4
