### ISSUE TITLE
Feature: Clarification on How To Create Progress Journals

### ISSUE THREAD

**Issue by adiati98** [open-sauced/100-days-of-oss-template#7]
### Type of feature

🍕 Feature

### Current behavior

At the moment the [Getting Started](https://github.com/open-sauced/100-days-of-oss-template#getting-started) section is as below:

  1. Fork this repository
  2. Clone your forked repository to your local machine
  3. Create a new branch for each day of the challenge if you want to keep your work separate
  4. Commit your work to your branch
  5. Push your changes to your forked repository
  6. Create a pull request to merge your changes into the main branch of your forked repository
  7. Repeat steps 3-6 for each day of the challenge

And the first bullet point in the tips section is:
> - Use the `table-of-contents.md` file to keep track of your work

#### The Concern

Probably folks who are not familiar with open source would get confused because of the lack of details and clarifications. Questions such as "Where should I write my progress? Is it in the `table-of-contents.md` or in other files?" "How to clone the repo and do commits?" etc. may arise.

### Suggested solution

- Add a couple of numbers in the Getting Started section to clarify the process. For example:

3. Create a new branch for each day ...
4. Create a new file and name it anything you like, e.g., `my-oss-journal.md`.  This will be the place where you update your #100DaysofOSS progress.
5. Use the template in the `journal.md` to record your progress.
6. Commit ...

- Make a nested bullet point in the [Tips](https://github.com/open-sauced/100-days-of-oss-template#tips-for-making-the-most-out-of-100daysofoss) section to explain how to update the `table-of-content.md` file. Something like:

  - Use the `table-of-contents.md` file to keep track of your work. To update the Table of Contents:
    - Open the `my-oss-journal.md` file (your progress journal file) on GitHub.
    - Click on the link icon at title of the day and copy the link.
    - Paste the link in the `table-of-contents.md`;
    
      ```
      - [Day 1](link-to-day-1#day-1)
      ```
    - Follow the steps in the [Getting Started](https://github.com/open-sauced/100-days-of-oss-template#getting-started) to commit, push and create pull request to merge your changes into the main branch of your forked repository. 

- Add code examples to clone, create a branch, commit, and push changes from local to remote environment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
Hi,
I would love to work on this issue if it's approved :)

Thank you!

**Comment by BekahHW** [comment]
@adiati98 it's all you!

**Comment by adiati98** [comment]
Thanks, @BekahHW !

I just think of something else. While I'm on it, I could also give code examples to do the clone, commit, etc.

Any thoughts?

I can work on it altogether within this issue or create a separate issue and pull request if you prefer.

**Comment by BekahHW** [comment]
That sounds great, Ayu! It can all go in this one unless breaking it down is easier for you.

**Comment by adiati98** [comment]
Awesome! I'll edit the issue to mention it as well and do them all in one pull request 😊

Work on it soon! 🙌🏼

**Comment by adiati98** [comment]
@BekahHW I have a couple questions.

- Currently in the `table-of-contents.md` file, we have this structure:

  ```markdown
  # 100 Days of Open Source

  ## Table of Contents

  - [100 Days of Open Source](#100-days-of-open-source)
    - [Table of Contents](#table-of-contents)
    - [Introduction](#introduction)
    - [Day 1](#day-1)
  ```

  Because we already have the "100 Days of Open Source" and "Table of Contents" titles, could we remove the bullet points of:

  ```markdown
    - [100 Days of Open Source](#100-days-of-open-source)
    - [Table of Contents](#table-of-contents)
  ```
  I'm thinking they don't have any function here.

  If we remove them, then the new structure would be:
  ```markdown
  # 100 Days of Open Source

  ## Table of Contents

    - [Introduction](#introduction)
    - [Day 1](#day-1)
  ```

- Second questions is, what is the purpose for the "Introduction" in Table of Contents?
  - Is it for participants to do their self-intro?
  - Is it to link to README? 
  - Anything else?

  Do we still want to keep it? If so, we need to clarify this as well in the docs.

**Comment by BekahHW** [comment]
> @BekahHW I have a couple questions.
> 
> * Currently in the `table-of-contents.md` file, we have this structure:
>   ```
>   # 100 Days of Open Source
>   
>   ## Table of Contents
>   
>   - [100 Days of Open Source](#100-days-of-open-source)
>     - [Table of Contents](#table-of-contents)
>     - [Introduction](#introduction)
>     - [Day 1](#day-1)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Because we already have the "100 Days of Open Source" and "Table of Contents" titles, could we remove the bullet points of:
>   ```
>     - [100 Days of Open Source](#100-days-of-open-source)
>     - [Table of Contents](#table-of-contents)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   I'm thinking they don't have any function here.
>   If we remove them, then the new structure would be:
>   ```
>   # 100 Days of Open Source
>   
>   ## Table of Contents
>   
>     - [Introduction](#introduction)
>     - [Day 1](#day-1)
>   ```
> * Second questions is, what is the purpose for the "Introduction" in Table of Contents?
>   
>   * Is it for participants to do their self-intro?
>   * Is it to link to README?
>   * Anything else?
>   
>   Do we still want to keep it? If so, we need to clarify this as well in the docs.

@CBID2, do you have answers to the questions above?

**Comment by CBID2** [comment]
Hi @adiati98. The intro is where participants would introduce themselves and why they are doing this challenge. However, if they want to put it elsewhere, they can. The template is customizable. I'll raise an issue to emphasize this point in the docs.
