### ISSUE TITLE
Feature: add notion and add community

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/100-days-of-oss-template#9]
### Type of feature

🍕 Feature

### Current behavior

I have created a notion page based on my conversation with @BekahHW 

Here is the link for it: https://a0m0rajab.notion.site/100-Days-Of-Open-Source-2615e66772e14152897002e348c5f1bc?pvs=4

Plus, I was thinking that it would be nice to have a place where we can add the links to the repos/journals of people who joined the challenge where it would play as a showcase place for them, but I was not sure where should we add this? 

It might be as a new total repo or within the highlights. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
Hey, @a0m0rajab do you want to make a PR to add this into the [#100Days docs](https://docs.opensauced.pizza/)
